# [Auto-Generated File]
REVIEW_JSON = {
  "description1": "这份文档记录了所有在“专案组”模块中可能提及的问题。这既是技术文档也是用户文档。",
  "description2": "所有评判的细节都可以在这份文档中找到，同时文档也提供了json格式的所有接口及话术。",
  "description3": "json中必然会包含这三个字段：",
  "description4": "`code` 问题编号，唯一代表了所指定的问题。",
  "description5": "`status` 状态，指错误的严重程度，通常`0`代表正确，`1`代表轻微问题，`2`代表中等问题，`3`代表严重问题。",
  "description6": "每个问题不一定包含了所有的状态。",
  "description7": "`rate` 评分，100分为最好，0分为最差。这个评分会直接影响状态，也会作为结果显示。",
  "description8": "这份文档本身是json格式，是用于全流程中自动化生成话术的自动生成。",
  "description9": "review的结果也是json格式，用于作为展示界面的输入，请注意区分。",
  "content": [
    {
      "code": 1,
      "title": "不要死",
      "num": "重伤的次数",
      "duration": "重伤的总时间",
      "rate": "当`num`=0时为100%，否则为0%。",
      "threshold": [1, 1, 1, 0],
      "descCondition": [3],
      "desc": "所有的重伤都可以避免，请尝试躲避技能，正确处理机制。重伤会产生非常大的影响，不仅会极大程度降低你的团队贡献，而且增加了战斗失败的可能。",
      "addCondition": [3],
      "add": "你重伤了`num`次，期间浪费了`duration`的时间。"
    },
    {
      "code": 10,
      "title": "不要放生队友",
      "num": "放生的次数",
      "time": "数组格式，放生的时间",
      "id": "数组格式，队友ID",
      "damage": "数组格式，队友受到的伤害名及伤害量",
      "rate": "当`num`=0时为100%，否则为0%。",
      "threshold": [1, 1, 1, 0],
      "descCondition": [3],
      "desc": "如果你的队友没有受到不可挽救的伤害，你就应当对其进行治疗以避免重伤。请记住，治疗职业的第一优先级永远是保证团队成员的存活，不要为了刷治疗量放弃队友。有时拯救队友需要快速的反应或者预判，这取决于你对副本的理解。",
      "addCondition": [3],
      "add": "你放生了`num`次队友：",
      "addArrayCondition": [3],
      "addArray": "`time`，`id`：`damage`"
    },
    {
      "code": 11,
      "title": "保持gcd不要空转",
      "cover": "战斗效率",
      "rank": "天网排名",
      "rate": "等于`rank`",
      "threshold": [75, 50, 25, 0],
      "descCondition": [1, 2, 3],
      "desc": "保持使用技能是战斗的基础。只要你持续处于读条或者转gcd的状态，就一定比站在原地发呆好。记得为可能产生的移动做好准备，在移动时也可以使用瞬发技能。",
      "addCondition": [0, 1, 2, 3],
      "add": "你的战斗效率为`cover`，超过了`rank`的玩家。",
    },
    {
      "code": 12,
      "title": "提高HPS或者虚条HPS",
      "hps": "HPS",
      "ohps": "虚条HPS",
      "hpsRank": "HPS的排名",
      "ohpsRank": "虚条HPS的排名",
      "rate": "为`hpsRank`与`ohpsRank`的较大者",
      "threshold": [75, 50, 25, 0],
      "descCondition": [1, 2],
      "desc": "HPS仍然是副本中评价治疗职业的公认标准，保证充足的HPS可以为团队提供更高的容错。在副本环境中，很多时候你需要用溢出治疗来保证血量健康，因此虚条HPS也可以是指标的一部分。",
      "addCondition": [0, 1, 2],
      "add": "你的HPS为`hps`，超过了`hpsRank`的玩家；虚条HPS为`ohps`，超过了`ohpsRank`的玩家。"
    },
    {
      "code": 13,
      "title": "使用有cd的技能",
      "cover": "技能使用率",
      "skill": "数组格式，技能名",
      "num": "数组格式，使用次数",
      "sum": "数组格式，总次数",
      "rate": "等于`cover`",
      "threshold": [50, 25, 0, 0],
      "descCondition": [1, 2],
      "desc": "有cd的技能大多都是十分强力的。虽然说有时这些技能应当用来救急，但是如果战斗中它们空转了过长的时间，你就应该去重新安排它们。",
      "addCondition": [0, 1, 2],
      "add": "技能使用情况：",
      "addArrayCondition": [0, 1, 2],
      "addArray": "`skill`：(`num`/`sum`)"
    },
    {
      "code": 90,
      "title": "敬请期待",
      "rate": "固定为0%",
      "threshold": [100, 0, 0, 0],
      "descCondition": [1],
      "desc": "这个心法的功能还没有完全实现，敬请期待！"
    },
    {
      "code": 101,
      "title": "不要玩血歌",
      "num": "有没有玩血歌",
      "rate": "当`num`=0时为100%，否则为0%。",
      "threshold": [1, 1, 1, 0],
      "descCondition": [3],
      "desc": "只要不是全程持续伤害类型的副本，血歌的作用就永远比盾歌低。`梅花三弄`附带的化解和减伤同样可以减少团队血量的压力，并且还能带来输出增益，“团血崩了”绝不是你切血歌的理由。"
    },
    {
      "code": 102,
      "title": "保证`梅花三弄`的覆盖率",
      "cover": "覆盖率",
      "rank": "天网排名",
      "rate": "等于`rank`",
      "threshold": [50, 25, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`梅花三弄`的覆盖率是奶歌最重要的指标，保证覆盖率可以增加团队输出，同时也为团队血量提供保障。多数时候，即使面对血量不满的目标也应当贴盾，让其它治疗来奶满。",
      "addCondition": [0, 1, 2, 3],
      "add": "覆盖率为`cover`，超过了`rank`的玩家。"
    },
    {
      "code": 103,
      "title": "中断`徵`的倒读条",
      "time": "次数",
      "perfectTime": "正确中断次数",
      "fullTime": "未中断次数",
      "rate": "等于`perfectTime`/`time`",
      "threshold": [50, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`徵`应当在读条过半时中断（带有`争簇`时为第3跳，无`争簇`时为第2跳），这样可以最大化利用`弄梅`；特别是当点出`谪仙`时，不中断会导致损失徵的跳数。",
      "addCondition": [0, 1, 2, 3],
      "add": "你总共运功了`time`次徵，但只正确中断了`perfectTime`次，其中有`fullTime`次完全没有进行中断。"
    },
    {
      "code": 104,
      "title": "选择合适的`徵`目标",
      "time": "次数",
      "coverTime": "覆盖人数正常的徵次数",
      "rate": "等于`coverTime`/`time`",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`徵`会以当前目标中心进行20尺扩散，因此选择正确的目标可以让更多队友受到治疗效果。使用茗伊团队面板的扩散辅助可以精准地找到最适合的目标。",
      "addCondition": [0, 1, 2, 3],
      "add": "你总共施放了`time`次徵，但只有`cuttime`次覆盖了4个或更多的目标。"
    },
    {
      "code": 105,
      "title": "使用`移形换影`",
      "time": "放影子的次数",
      "coverTime": "吃影子的次数",
      "wasteTime": "没有吃到影子的次数",
      "rate": "等于`covertime`/`time`",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "记得使用`移形换影`去回收影子以维持健康的内力，从而弥补贴盾的大量消耗。",
      "addCondition": [0, 1, 2, 3],
      "add": "你浪费了`wasteTime`次影子提供的回蓝。"
    },
    {
      "code": 106,
      "title": "使用`角`",
      "cover": "角的整体覆盖率",
      "rate": "吃影子的次数",
      "threshold": [50, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "记得保持`角`的覆盖以维持健康的内力，从而弥补贴盾的大量消耗。角的持续治疗效果对主T的血量也是可观的支持。"
    },
    {
      "code": 201,
      "title": "保证`秋肃`的覆盖率",
      "cover": "覆盖率",
      "rank": "天网排名",
      "rate": "等于`rank`",
      "threshold": [75, 50, 25, 0],
      "descCondition": [1, 2, 3],
      "desc": "`秋肃`会为团队带来可观的输出增益，是奶花在副本中可以提供的最有效的门票。尝试通过各种监控方式去适应秋肃的手感，绝对不要让增益中断。",
      "addCondition": [0, 1, 2, 3],
      "add": "覆盖率为`cover`，超过了`rank`的玩家。"
    },
    {
      "code": 202,
      "title": "保证`握针`的覆盖率",
      "cover": "覆盖率",
      "rank": "天网排名",
      "rate": "等于`rank`",
      "threshold": [75, 50, 25, 0],
      "descCondition": [1, 2, 3],
      "desc": "`握针`是奶花最重要的治疗量来源，尽可能使全团保持这个效果。`握针`的数量也是评判奶花手法最重要的依据。",
      "addCondition": [0, 1, 2, 3],
      "add": "覆盖率为`cover`，超过了`rank`的玩家。"
    },
    {
      "code": 203,
      "title": "不要浪费瞬发次数",
      "timeShuiyue": "水月次数",
      "timeXqx": "行气血次数",
      "timeCast": "用掉的瞬发次数",
      "rate": "等于(3)/(1+2)",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`行气血`与`水月无间`提供的瞬发效果可以让你无损瞬发技能，但是如果时间用尽或者被新的`行气血`顶掉就会失去这些机会。尽可能利用好这些瞬发次数。",
      "addCondition": [0, 1, 2, 3],
      "add": "你获得了`timeShuiyue`层水月，`timeXqx`层行气血，但你只使用了其中的`timeCast`次。"
    },
    {
      "code": 204,
      "title": "优先瞬发`长针`",
      "timeCast": "水月次数",
      "timeChangzhen": "行气血次数",
      "rate": "等于2/1",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "尽可能使用瞬发效果去瞬发`长针`，这可以为你节省一个gcd的时间；瞬发`提针`与`彼针`不能为你节省gcd时间，除非这一个gcd可以用来救急，否则不应该这样瞬发。",
      "addCondition": [0, 1, 2, 3],
      "add": "你使用了`timeCast`次瞬发，但只有`timeChangzhen`次用于长针。"
    },
    {
      "code": 205,
      "title": "选择合适的`长针`目标",
      "time": "长针次数",
      "covertime": "覆盖人数正常的长针次数",
      "rate": "等于`covertime`/`time`",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`微潮`会以当前目标中心进行15尺扩散，因此选择正确的目标可以让更多队友受到`握针`的效果。使用茗伊团队面板的扩散辅助可以精准地找到最适合的目标。",
      "addCondition": [0, 1, 2, 3],
      "add": "你总共触发了`time`次微潮，但只有`covertime`次覆盖了4个或更多的目标。"
    },
    {
      "code": 206,
      "title": "提高握针扩散效率",
      "cover": "握针平均扩散的数量",
      "rate": "等于`cover`/4",
      "threshold": [75, 0, 0, 0],
      "descCondition": [1, 2, 3],
      "desc": "`微潮`只能将`握针`扩散到身上没有`握针`的目标，所以使用时不仅要保证目标身上有`握针`，还要让对应小队的`握针`数量越少越好。如果小队中`握针`还没有跳完，就应当改用`束彼`去刷新，或是等待其时间结束。",
      "addCondition": [0, 1, 2, 3],
      "add": "理想情况下每次微潮应该扩散4个目标，但你平均扩散了`cover`个目标。"
    }
  ]
}



